pipeline {
    agent any

    tools {
      terraform 'Terra-1.3'
    }

    stages {
        stage('Git Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://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@github.com/cevl/Ejercicio5']]])
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'cd terraform'
                sh 'terraform init'
                sh 'terraform apply --auto-approve'
            }
        }
    }
}