pipeline {
    agent any

    tools {
      terraform 'Terra-1.3'
    }

    stages {
        stage('Git Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://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@github.com/cevl/Ejercicio5']]])
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                dir('terraform') {
                    sh 'terraform init'
                    sh 'terraform apply --auto-approve'
                }
            }
        }
    }
}