pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                cd terraform
                terraform init
                terraform apply
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}